### ISSUE TITLE
Extension not enabling

### ISSUE THREAD

**Issue by Relms12345** [idleberg/vscode-nsis#16]
I am on VSCode Insiders and for some reason when i install this plugin, It does not want to enable at all. I tried restarting vscode, my computer and re-installing the plugin. Can someone help?

**Comment by tehKaiN** [comment]
I'm not on insiders and have same problem. Help! :(

**Comment by idleberg** [comment]
Thanks for reporting. The problem was caused by a dependency loop:

```
abstractExtensionService.ts:396 The following extensions contain dependency loops and have been disabled: 'idleberg.bridlensis', 'idleberg.nsis'
```

Some background info: I'm planning to deprecate BridleNSIS support since the project has been dormant for years. To make the transition for BridleNSIS users as smooth as possible, support has been outsourced to a separate package. This package is currently a dependency of `vscode-nsis`. This dependency will be removed in the next major version to complete the deprecation.

Anyway, upgrading (or disablig) `vscode-bridlensis` should fix the issue.

**Comment by tehKaiN** [comment]
Fixed for me!

**Comment by Relms12345** [comment]
Nope not fixed for me unfortunately. I'll just wait for the next update

**Comment by idleberg** [comment]
@Relms12345 Did you update (or disable) `vscode-bridlensis`? If so, did you restart VSCode? Otherwise, can you please post related errors from the Developer Tools console (see *Help > Toggle Developer Tools*)?
